import { Outfit } from "next/font/google";
import "./globals.css";

// Components
import Header from '@/components/Header';
import Footer from '@/components/Footer';
// Theme Provider
import { ThemeProvider } from '@/components/ThemeProvider';

import { Toaster } from "@/components/ui/toaster"

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "TJS Designs | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${outfit.className} antialiased font-sans`}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <Header />
          {children}
          <Toaster />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
